### ISSUE TITLE
Observer location not in calculation of Moon  position.

### ISSUE THREAD

**Issue by al-davis** [cosinekitty/astronomy#123]
I'm at 43 deg N and am seeing large errors in Moon Declination angle.  Reported Moon Declination errors decrease to near zero if I assume I'm near the equator.  I do not think observer location is in the calculation of Moon  position.

I'm Comparing output generated using this code with program Stellaruim (stellarium.org)

**Comment by cosinekitty** [comment]
Hi @al-davis, I will be happy to help. Can you post the code you are using to calculate the moon's declination?

**Comment by al-davis** [comment]
> Hi @al-davis, I will be happy to help. Can you post the code you are using
> to calculate the moon's declination?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/cosinekitty/astronomy/issues/123#issuecomment-929184313




//  This is the relevant section of my code used to get Moon location

//--------------------------------------------------
//
// This generates numDays  the time supplied to routine GetMoonLocation()
//
//-------------------------------------------------

void CalcNumDays()
{
HHMMSS tPos;
float HMS=0.0;
double baseYears = (365*16) + (366*5);    // 2021
int currYear = (RTC.t.year-2021)*365;
int leapYears=0;

//           is it  DST
double UTC = RTC.t.isdst ? 4.0/24.0 : 5.0/24.0;  // EST offset to UTC hrs
fraction of day (1) 4hr & 5hr & account for daylight savings time

// Fraction of day offset cause noon is time of day w/o correction. -0.5
set to Midnight ie 12h before Noon
float FOD = 0.5;


   // HMS is fraction of day elapsed since midnight
   HMS =((RTC.t.sec + (RTC.t.mn * 60) + (RTC.t.hr * 3600L)) / 86400);


   for(int yy=2021;yy<=RTC.t.year;yy++)
     if(yy % 4 == 0)                         // 24 28 32 36 etc leaps
       leapYears++;


   numDays =  baseYears + currYear + RTC.t.yday + leapYears +UTC -FOD
+HMS;   //   RTC.t.yday is day of year

   return;
}

//--------------------------
//
// This added to astronomy.c
// All underlying code in astronomy.c unaltered
//
// This is called with the output ( numDays ) of above routine ( 
CalcNumDays()  )
// Example for Date & Time  9-28-2021  14:00  (DST)  value of numDays is :
//
// Using input numDays : 7941.250046
// Output from here is :
// RA =  RA:6.1396983   6:8:22.914
// Dec = 25.8914901   25°53'29.364"
//
// Stellarium output for same date & time (J2000.0) is :
// RA =  6h 05m 26.93s
// Dec = +25° 17' 05.0"
//
//--------------------------

double GetMoonLocation(double numDays, double *dec)
{
  astro_time_t t;
  astro_equatorial_t Re;
  astro_vector_t Rv;

  t.tt = numDays;

  Rv = Astronomy_GeoMoon(t);
  Re = Astronomy_EquatorFromVector(Rv);

  *dec = Re.dec;
  return(Re.ra);
}



// program generated output used in this example

2021.09.28 Tue (271) ---RTC--- 14:00: 4.0  DST (1)  // 271 is day of year 
4hr ofset fron UTC
CalcNumDays() HMS:0.583380 numDays:7941.250046
DetermineMoonPos()  RA:6.1396983   6:8:22.914
DetermineMoonPos() Dec:25.8914901   25°53'29.364"

**Comment by cosinekitty** [comment]
OK, this should work a lot better. As you pointed out, you need the geographic coordinates to adjust for parallax of the Moon, because it is so close to the Earth. Also, it is a good idea to use either `Astronomy_TimeFromDays` or `Astronomy_TerrestrialTime` to create the time value. Directly putting `tt` in the struct might appear to work, but leaving other parts of that structure undefined will cause unpredictable problems, depending on what random values end up there.  You might even take advantage of the following function if you know the calendar date and time:

```C
astro_time_t Astronomy_MakeTime(int year, int month, int day, int hour, int minute, double second);
```

Here is an example of calculating the Moon's position based on the observer's geographic coordinates:

```C
#include <stdio.h>
#include "astronomy.h"

int main(void)
{
    astro_equatorial_t equ;
    astro_time_t time;
    astro_observer_t observer;

    const double numDays = 7941.250046;

    observer.height = 0.0;
    observer.latitude = 43.0;
    observer.longitude = -90.0;     /* Please adjust with your longitude. */

    /*
        I don't know whether you need legal/civil time adjusted with leap seconds (UTC)
        or terrestrial time (TT). Most people need UTC, so this will work better:
    */
    time = Astronomy_TimeFromDays(numDays);

    /*
        If your time base is really based on astronomical TT, replace
        the above time calculation with this...

        time = Astronomy_TerrestrialTime(numDays);
    */

    equ = Astronomy_Equator(BODY_MOON, &time, observer, EQUATOR_J2000, ABERRATION);
    printf("Moon position: RA=%0.3lf hours, DEC = %0.3lf degrees\n", equ.ra, equ.dec);
}
```

I hope this helps!

**Comment by al-davis** [comment]
Wow !  Much better, pays to know what you're doing.
Thank you.

2021.09.28 Tue (271) ---RTC--- 17:16:23.0  DST (1)
RA:6.2352628   6:14:6.946
Dec:25.1896504   25°11'22.741"

Stellarium :

RA : 6h 14m 4.23s
Dec :+25 11' 20.8"

**Comment by al-davis** [comment]
Another question.  I'm using the code modifications you suggested in our past conversation & have added location info and  routine Astronomy_Horizon(...).
 
All is well except the value astro_horizon_t hor.altitude .  Comments state  Angle in degrees above the observer's horizon.

Sample values output :

2021.10.14 Thu (287) ---RTC--- 20:51:12.0  DST (1)      // Oct 14, 2021  20:51:12 
HMS:0.868889 nDays:7957.535600             // here nDays is  numDays in   Astronomy_TimeFromDays(numDays); 
RA:21.3128050   21:18:46.099                    // astro_equatorial_t  equ.ra
Dec:-21.75363  -21°-45'-13.074"                // astro_equatorial_t  equ.dec
Az:172.16031 Alt:25.74174 aRA:21.31281 aDec:-21.75363   // astro_horizon_t hor.azimuth  hor.altitude hor.ra  hor.dec

Stellaruim and my eyes looking at the Moon show it much higher in the sky than 25 deg, maybe 70 deg or so. 
hor.altitude  shows as near 0 deg when on the horizon.

Do I misunderstand something ?  Setup issue ?


//---------------------------------------------------------------------------------------------------------------

double GetMoonLocation(double numDays, double *dec, double *az, double *alt, double *rr, double *dd)
{
astro_equatorial_t equ;
astro_time_t time;
astro_observer_t observer;

    observer.height = 295.9608;     // meters  971 ft
    observer.latitude = 42.11xxxx;  // My house  xxx's for inet security
    observer.longitude = -84.16xxxx;    

    time = Astronomy_TerrestrialTime(numDays);   

    equ = Astronomy_Equator(BODY_MOON, &time, observer, EQUATOR_J2000, ABERRATION);   
    
    astro_horizon_t hor = Astronomy_Horizon(&time, observer, equ.ra, equ.dec, REFRACTION_NORMAL);

    //astro_time_t *time, astro_observer_t observer, double ra, double dec, astro_refraction_t refraction)
    //double azimuth;     /**< Compass direction around the horizon in degrees. 0=North, 90=East, 180=South, 270=West. */
    //double altitude;    /**< Angle in degrees above (positive) or below (negative) the observer's horizon. */
    //double ra;          /**< Right ascension in sidereal hours. */
    //double dec; 

    *az = hor.azimuth;
    *alt = hor.altitude; 
    *rr = hor.ra;
    *dd = hor.dec; 
    *dec = equ.dec;
    return(equ.ra);
}

**Comment by al-davis** [comment]
Yes, Southern MI near Jackson.  It's raining & clouded over here tonight
but I checked the Moon last night about 9pm and it seemed above 45 deg
with the report saying 24 deg Altitude. I just made a careful measurement
on Stellarium and it matches well with the reported Altitude.
    I may have a measurement/perception issue here.  There are trees to my
South and I may be misjudging where the horizon is.  I need to make a
careful measurement when it's clear. Sounds like I don't have a setup
problem and am not misunderstanding the value.  Thanks for helping.

**Comment by cosinekitty** [comment]
OK, that makes sense. There are a couple of things you can do to make the code slightly more accurate, but I didn't mention them before because the difference is rather small (nothing like 25 degrees versus 70 degrees).

First, I would recommend using a function other than `Astronomy_TerrestrialTime` to convert time. Almost everyone is using UTC (civil time read from a clock), not TT (terrestrial time without leap seconds, used by astronomers). To calculate the current time according to the computer's internal clock, use:

```C
astro_time_t time = Astronomy_CurrentTime();
```

To use a specific civil time in the past or future, use one of the following:

```C
astro_time_t time = Astronomy_TimeFromDays(numDays);
```

or

```C
// From UTC date/time: Astronomy_MakeTime(year, month, day, hour, minute, second)
astro_time_t time = Astronomy_MakeTime(2021, 10, 15, 20, 30, 0.0);
```

The second thing is, when you are calculating horizontal coordinates, you should feed it RA/DEC based on equator-of-date instead of the J2000 equator. So that means use `EQUATOR_OF_DATE` instead of `EQUATOR_J2000` in:

```C
equ = Astronomy_Equator(BODY_MOON, &time, observer, EQUATOR_OF_DATE, ABERRATION);
```

Sometimes in my own code I have to calculate both J2000 equatorial coordinates (for comparing with known star positions) and of-date equatorial coordinates (to get accurate horizontal coordinates from them). In those cases I call `Astronomy_Equator` twice, and make two variables `equ_2000` and `equ_date`, to keep them straight in my mind.

Again, these are minor corrections, but it will help to get the most accurate horizontal coordinates.
