### ISSUE TITLE
Support building Astronomy Engine on Mac

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#142]
This code base already supports using Linux or Windows as development platforms for maintaining and improving Astronomy Engine. (Note that the pre-generated code should work on any platform; I am talking about making changes to Astronomy Engine, not using it as-is.) Currently I do not own a Mac, so I have no way of testing there. It would be great if a developer with a Mac wanted to volunteer to get the build process working on that platform too.

**Comment by ebraminio** [comment]
Apparently this issue is filed for me :)

The first thing I needed was doxygen which just installed it from brew with `brew install doxygen`
 
The first issue is the `./run` script relies on sha256sum which isn't available which can be resolved with `brew install coreutils`.

For the python part I installed pylint using `pip3 install pylint`.

But now got this issue,

```
2c2
< Moon check: x = 1.0000e+00, y = -2.0726e-16, z = -8.2904e-17
---
> Moon check: x = 1.0000e+00, y = -2.0726e-16, z = -1.0363e-16
FATAL(~/astronomy/demo/c/test/test): Error comparing camera.c output.
```

Maybe is because of my timezone or something? Most of the tests just work without any issue so guess this should be trivial issue, at least hopefully.

**Comment by ebraminio** [comment]
Guess the best way to ensure it is working as expected is to put it on CI, https://github.com/ebraminio/astronomy/commit/dd2d54655d3e1b4ffac4785f7c497224710748db 

https://github.com/ebraminio/astronomy/runs/4733627170

**Comment by ebraminio** [comment]
Thanks! :) There is also a Windows one,

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

Please note that there are cool trick to get SSH access to the bot https://blog.benoitblanchon.fr/github-action-run-ssh-commands/ in order to debug a machine you don't have in hand.

**Comment by ebraminio** [comment]
Edit: fixed the link

**Comment by ebraminio** [comment]
Sure, contributing back to the project is what I wanted from the beginning :) Here you go https://github.com/cosinekitty/astronomy/pull/145 :)

**Comment by ebraminio** [comment]
Fails on https://github.com/ebraminio/astronomy/runs/4733627170?check_suite_focus=true

**Comment by cosinekitty** [comment]
> Fails on https://github.com/ebraminio/astronomy/runs/4733627170?check_suite_focus=true

This is great. Thank you for your help on this!

Yes, I have some more work to do before I bring this into the master branch. Here is what I will do tonight (it is morning here in Florida).  I found manual instructions for bringing your pull request locally to my own system, in a new topic branch. I will keep working through the remaining issues until they pass CI on Linux and macOS both. Then I will merge the result into the master branch.

I will make sure you are also listed as a contributor to Astronomy Engine on the GitHub page.
