### ISSUE TITLE
.NET 4.8 compilation error

### ISSUE THREAD

**Issue by evo11x** [cosinekitty/astronomy#162]
I get this error when I try to compile the astronomy.cs file with VS2019 / .NET 4.8

`Error CS0117 'double' does not contain a definition for 'IsFinite'`

Line: 8591

**Comment by cosinekitty** [comment]
Thank you for the helpful report. I do all my development and testing using .NET Core 6, which is why I didn't notice this. However, I do want to maintain compatibility with .NET Framework 4. The commit 871389c9cf7fb5b9f479721e89d5614f097cdc08 resolves the compiler error. Can you please let me know here whether `astronomy.cs` now compiles in your project?

**Comment by evo11x** [comment]
Yes, now it compiles. Thanks !

**Comment by cosinekitty** [comment]
Great! Please let me know if you have any other issues, or questions about the code or astronomy calculation in general.

**Comment by evo11x** [comment]
I want to get the planet positions for a given latitude and longitude from earth, but it seems more complicated than CoordinateSharp which I used before. The problem with Coordinate sharp is that it returns only sun and moon positions.

**Comment by cosinekitty** [comment]
Yes, I can help with that. What kind of position are you interested in? Equatorial (RA/DEC), horizontal (altitude/azimuth), or something else?
