### ISSUE TITLE
Crash on searchLocalSolarEclipse

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#227]
I got this very rare crash in my app from one of the users from Google Play console,

```
io.github.cosinekitty.astronomy.EarthNotAllowedException: 
  at io.github.cosinekitty.astronomy.Astronomy.peakLocalMoonShadow (Astronomy.java)
  at io.github.cosinekitty.astronomy.Astronomy.searchLocalSolarEclipse (Astronomy.java)
  at com.byagowi.persiancalendar.ui.astronomy.AstronomyState.generateHeader (AstronomyState.java)
  ...
```

Unfortunately Play console doesn't provide any other context with the crash guess because of privacy reasons and guess some of the intermediary function calls are removed due to compiler optimizations. Does it remind you of something? Maybe the user had a weird combination of latitude longitude or has moved to a long distant time to make this crash? It should be a very rare one and it has happened only once given all the users, still. Thanks!

**Comment by cosinekitty** [comment]
There is definitely something wrong with that stack trace. I keep looking, but it is not possible for `peakLocalMoonShadow` to call any other function that will throw `EarthNotAllowedException`. I don't know enough about JVM... is it possible there is an incorrect symbols file that leads to a wrong stack trace? This can happen in other languages.

Here is the more likely stack trace, if it really is coming from `searchLocalSolarEclipse`. 

- EarthNotAllowedException
    - pairLongitude
        - moonPhase
            - searchMoonPhase
                - searchLocalSolarEclipse

But this isn't possible either, because `pairLongitude` will throw that exception if either of the body parameters is Earth, but `moonPhase` does not do that:

```kotlin
fun moonPhase(time: Time): Double =
    pairLongitude(Body.Moon, Body.Sun, time)
```

This leaves me with the conclusion we can't trust that stack trace at all. Solving this will require a different way of thinking.

With that in mind, here is a complete tree of all possible stacks where `EarthNotAllowedException` could be thrown:

- EarthNotAllowedException
    - pairLongitude
        - moonPhase
            - searchMoonPhase
                - searchLunarEclipse
                    - nextLunarEclipse
                    - lunarEclipsesAfter
                - searchGlobalSolarEclipse
                    - nextGlobalSolarEclipse
                    - globalSolarEclipsesAfter
                - searchLocalSolarEclipse
                    - nextLocalSolarEclipse
                    - localSolarEclipsesAfter
            - searchMoonQuarter
                - nextMoonQuarter
                    - moonQuartersAfter
                - moonQuartersAfter
        - elongation
            - searchMaxElongation
    - searchHourAngle
        - internalSearchAltitude
    - internalSearchAltitude
        - searchRiseSet
        - searchAltitude
    - angleFromSun
        - searchTransit
            - nextTransit
            - transitsAfter
    - illumination
        - magnitudeSlope
            - searchPeakMagnitude
        - searchPeakMagnitude

Can you provide a list of which of the functions above you know you ever call from your project? Then we can start to narrow down possible ways the exception could happen.

**Comment by ebraminio** [comment]
>  is it possible there is an incorrect symbols file that leads to a wrong stack trace?

Possible as lots of magics going on, obfuscation, optimization and minimization, de-obfuscation. 

> Can you provide a list of which of the functions above you know you ever call from your project? Then we can start to narrow down possible ways the exception could happen.

The app has multiple use of astronomy on different place but assuming this happened in its astronomy screen as trailing part of crash log suggest, these are the call used on that screen https://github.com/persian-calendar/persian-calendar/blob/main/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/astronomy/AstronomyState.kt#L17-L22 and this `AstronomyState` is an one time object.

**Comment by cosinekitty** [comment]
I spent some time looking through your code, and I still don't see how it is possible to cause `EarthNotAllowedException`. It is definitely not possible to cause it from `peakLocalMoonShadow`.  I start to wonder if this is a hardware error, like bad RAM or overheated system? I hate to blame it on hardware, but I don't see any possible way for `searchLocalSolarEclipse` (or any other things you call) to cause this exception.

**Comment by ebraminio** [comment]
I don't see why not, so let me close till more evidence show up, thanks :)
