### ISSUE TITLE
Planets positions in ThreeJs enviroment

### ISSUE THREAD

**Issue by AfarsheziF** [cosinekitty/astronomy#229]
Hello all. A beginner question.

I recently discovered astronomy.js while working on a client project, and the project looks great!

I like to calculate the current solar system planets positions and set it on a **ThreeJS** sketch.
Which functions should I use to convert the data to match an **XYZ system**? Is there a function to get the current distance of a planet from the sun?

I like to achieve a result similar to the 3D Solar System simulation of **TheSkyLive** (https://theskylive.com/3dsolarsystem).
As the simulation code is not available, I ask for your help here. 

Many thanks!

**Comment by cosinekitty** [comment]
Hello @AfarsheziF, and welcome to the Astronomy Engine project!  Yes, I can help you with this.

First you will want to look at the function [HelioVector](https://github.com/cosinekitty/astronomy/tree/master/source/js#HelioVector). This will return a 3D position vector for any solar system body at any moment in time.

In order to show the solar system from different angles, you can rotate the vector by different angles using the rotation matrix functions. For example, you can create an identity matrix (no rotation) using [IdentityMatrix](https://github.com/cosinekitty/astronomy/tree/master/source/js#IdentityMatrix). Then use the [Pivot](https://github.com/cosinekitty/astronomy/tree/master/source/js#Pivot) function to rotate the matrix by a given number of degrees, probably around the x-axis. Finally call [RotateVector](https://github.com/cosinekitty/astronomy/tree/master/source/js#RotateVector) giving it the pivoted rotation matrix and each 3D vector, to produce a rotated 3D vector.

When you graph the 3D position on a 2D surface, you can use the rotated vector's x-coordinate and y-coordinate, and ignore the z-coordinate.

**Comment by cosinekitty** [comment]
I realize I didn't answer part of your question. To calculate the distance of a planet from the Sun, once you have the 3D vector from HelioVector, you can call the vector's [Length](https://github.com/cosinekitty/astronomy/tree/master/source/js#vectorlength--number) method. This returns the number of astronomical units between the center of the Sun and the center of the planet.

**Comment by cosinekitty** [comment]
Hi @AfarsheziF, are you having good luck with the vectors and rotation matrices? Please let me know if I can provide any more help.

**Comment by AfarsheziF** [comment]
Dear @cosinekitty ! Thank you so much for replying to this case. I'm surly waiting to test your solution and come with results. Unfortunately the project has stopped and will continue in a month or so.
I'll post the results then.

Thanks again.

**Comment by cosinekitty** [comment]
@jffaust Yes, that is exactly right. Because every massive object in the solar system is pulling on every other object, orbits are not exactly the simple shapes one would at first think. So the Earth's movement is not confined to a single plane. However, the Earth does not wander away from the ecliptic plane very far; it stays quite close to that plane at all times.

However, the same cannot be said for the Moon. Its z-coordinate will be quite variable, no matter what coordinate system you use, because its movement is all over the place.  The Moon's orbit is one of the most complicated things to calculate, because it is a three-body interaction between the Sun, Earth, and Moon.

See the Wikipedia article [orbit of the Moon](https://en.wikipedia.org/wiki/Orbit_of_the_Moon) for more details.

I hope this helps. Feel free to drop more questions here. That sounds like a cool project you are working on. I would like to see it when you get it working.
