### ISSUE TITLE
Build Failing - macOS, Latest commits.

### ISSUE THREAD

**Issue by adamhill** [cosinekitty/astronomy#231]
Latest commit, macOS 12.4, homebrew indicates everything is up to date, `./run ` fails at:

```
./unit_test_js: Verifying elongation output.
CheckTestOutput: Verified 916 lines of file temp/js_longitude_Jupiter.txt
CheckTestOutput: Verified 469 lines of file temp/js_longitude_Mars.txt
CheckTestOutput: Verified 3153 lines of file temp/js_longitude_Mercury.txt
CheckTestOutput: Verified 994 lines of file temp/js_longitude_Neptune.txt
CheckTestOutput: Verified 997 lines of file temp/js_longitude_Pluto.txt
CheckTestOutput: Verified 966 lines of file temp/js_longitude_Saturn.txt
CheckTestOutput: Verified 988 lines of file temp/js_longitude_Uranus.txt
CheckTestOutput: Verified 626 lines of file temp/js_longitude_Venus.txt

./unit_test_js: SUCCESS.
./ctbuild: C compiler = gcc
ctest.c:1385:62: error: variable 'sum_diff' set but not used [-Werror,-Wunused-but-set-variable]
    double day_diff, min_diff = 1.0e+99, max_diff = 1.0e+99, sum_diff = 0.0;
                                                             ^
1 error generated.
ERROR(./ctbuild): Error building ctest
```
gcc is version 11.3.0_1

Anything else I shouldl check.

**Comment by cosinekitty** [comment]
Thank you for the report. That `sum_diff` variable was a fossil left over from an older version of the code. I just pushed a fix to the master branch. Can you pull and try again? There may be other warnings that are missed by the compilers I use for testing.

**Comment by adamhill** [comment]
That got it past the gcc error.

Now it can't find pylint ?! It is installed
```
CheckTestOutput: Verified 626 lines of file temp/c_longitude_Venus.txt
unit_test_c: success
Python 3.9.13
/usr/local/opt/python@3.9/bin/python3.9: No module named pylint
ERROR(./unit_test_python): pylint detected problems

❯ where pylint
/usr/local/bin/pylint
/usr/local/bin/pylint
/Users/adamhill/opt/anaconda3/bin/pylint
/usr/local/bin/pylint

❯ brew list pylint
/usr/local/Cellar/pylint/2.14.1/bin/epylint
/usr/local/Cellar/pylint/2.14.1/bin/pylint
/usr/local/Cellar/pylint/2.14.1/bin/pylint-config
/usr/local/Cellar/pylint/2.14.1/bin/pyreverse
/usr/local/Cellar/pylint/2.14.1/bin/symilar
/usr/local/Cellar/pylint/2.14.1/libexec/bin/ (19 files)
/usr/local/Cellar/pylint/2.14.1/libexec/lib/ (1505 files)
/usr/local/Cellar/pylint/2.14.1/libexec/pyvenv.cfg
```

Any ideas?

**Comment by cosinekitty** [comment]
I'm not sure yet, but what happens when you run `pylint --version` from the command line? Here is what it looks like on my Linux system:

```
$ pylint --version
pylint 2.11.1
astroid 2.8.0
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
```

Then try this to see if anything different happens:

```
$ python3 -m pylint --version
pylint 2.11.1
astroid 2.8.0
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
```

My best guess is that your installed pylint is for Python 2 instead of the required Python 3. Or maybe you have more than one version of Python 3 installed (doubtful)?

Another idea is to start with the command that is failing, and see if you can tweak it to make it work. (The following comes from the script `generate/unit_test_python`.) You need to be in the `generate` directory for this to work; otherwise pylint will not be able to find the configuration file `pylintrc`.

```
cd generate
python3 -m pylint  --init-hook="import sys; sys.setrecursionlimit(2000)" ../source/python/astronomy/astronomy.py
```

Also, I want to make sure that there is no misunderstanding about doing all this work. The vast majority of developers using Astronomy Engine don't need to do any of this. If you just want to use Astronomy Engine in another program, you don't need to get this working. What I check into GitHub is already pre-built. You only need to get the `generate/run` script working if you want to make changes to the Astronomy Engine source code, such as fixing bugs or adding new features. The purpose of the `run` script is to automate code generation and run unit tests before I publish to GitHub.

**Comment by adamhill** [comment]
Ah... Python version differences and I get clang as my compiler. But I see GCC actually running during the build / test. Hmm.

And the second command just straight up fails.

```
❯ pylint --version
pylint 2.14.1
astroid 2.11.5
Python 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]

❯ python3 -m pylint --version
/usr/local/opt/python@3.9/bin/python3.9: No module named pylint
```

I do realize I could just consume the Nuget or add the project, but I was hoping maybe to help out by writing a Mobile app example in for Android / iOS in Xamarin. I would like to eventually use it in a Mobile app myself so I was wanting to figure out how things build and how your data checking unit tests work.

I am just a little rusty in my command line build skills, I grew up on Make but have been spoiled by modern build systems and Azure DevOps :-) 

Thanks for the debugging suggestions.

**Comment by cosinekitty** [comment]
OK, so the Python version difference is the explanation. It looks like you have two different versions of Python 3 installed: 3.9 and 3.10. Pylint is installed in 3.9. The "clang" doesn't matter because that's just telling you what C compiler was used to build the Python 3.10 interpreter itself.

I think you can fix this just by installing pylint again for 3.10:

```
python3 -m pip install pylint
```

The idea with that command is it will use the same version of `python3` that is executed when the script `unit_test_python` runs, so everything should then be in sync.

That's great that you want to try using Astronomy Engine in a Xamarin project. I've always been interested in Xamarin, but I haven't gotten around to trying to do anything with it. I'll be interested in any comments or feedback you have about using Astronomy Engine with Xamarin.

**Comment by cosinekitty** [comment]
Hi @adamhill, just checking in. Is the Mac build process working for you now?

**Comment by adamhill** [comment]
Oops. Yes, builds are working, thanks!

 Do you have any .NET specific issues that you would like a second set of eyes on? Profiling? Any methods slower than you would like?  Any specific demos of functionality in a mobile app you would like to see?

**Comment by cosinekitty** [comment]
Hi @adamhill, it would be great to have a demo app that uses the device's GPS and clock to calculate the apparent horizontal positions (altitude and azimuth) of the Sun, Moon, and planets for the observer's location. It could start with text/numbers, but if you wanted to get fancy, use the device's compass heading to render a simple projected sky view that rotates with the phone. I can help with the math on that. What do you think?
