### ISSUE TITLE
Difference when built with -Ofast in Linux

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#245]
Apparently we are hitting something interesting in the C port,

Steps to reproduce:
1. Save the following file as a.cc
```C
#include <stdio.h>

#include "astronomy.h"

int main() {
    astro_time_t time = Astronomy_TimeFromDays(8301.6);
    astro_observer_t observer = { .latitude = 83, .longitude = -36, .height = .0 };
    astro_search_result_t s = Astronomy_SearchRiseSet(BODY_SUN, observer, DIRECTION_SET, time, 1);
    printf("%d\n", s.status);
    return 0;
}
```
2. Run
`gcc a.cc astronomy.c -lm -O3 && ./a.out`
3. Run
`gcc a.cc astronomy.c -lm -Ofast && ./a.out`

Expected:
Both should print 0

Actual:
`-O3` prints 0 but `-Ofast` prints 5.

Interestingly I don't see the issue in macOS with `-Ofast` or `-Ofastest`, I've seen the issue in four different Linux machines and it happens with both `clang` and `gcc` in Linux so perhaps not a compiler issue(!) but somehow platform dependent difference.

**Comment by cosinekitty** [comment]
My initial research led me to this [gcc bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25975) about the `-Ofast` option. The C version of Astronomy Engine currently uses NaN as a sentinel value to represent an unknown value. For example, [this check](https://github.com/cosinekitty/astronomy/blob/e9cf2a04177039f5726a7b70efca2ad1624c1687/source/c/astronomy.c#L1645) for whether sidereal time has yet been calculated in an instance of `astro_time_t`.

If I am understanding correctly, enabling `-Ofast` will cause `isnan` to always return false, meaning sidereal time will never be calculated. This would make it impossible to calculate anything related to the rotation of the Earth.

I will investigate more and report back on this thread later. But for now, I recommend avoiding this optimization because it is so aggressive that it will produce incorrect behavior in Astronomy Engine.

If I can confirm this optimization should not be used, my opinion is the best change to Astronomy Engine would be to detect the optimization and generate a compiler error, rather than allow invalid code to be produced.

**Comment by cosinekitty** [comment]
I was able to confirm my suspicions about `isnan`:

```bash
$ more nan.c
#include <stdio.h>
#include <math.h>

int main()
{
    double x = NAN;
    int f = isnan(x);
    printf("%d\n", f);
    return 0;
}
$ gcc -o nan nan.c && ./nan
1
$ gcc -o nan nan.c -Ofast && ./nan
0
```

**Comment by cosinekitty** [comment]
I made a change in fc21b4c0f17cd6d07f9bfbc1033c5e1286e8bdcf that will cause a compiler error in gcc if someone tries to use `-Ofast` to build the C version of Astronomy Engine. I recommend using `-O3` for optimization, because that is what I use for all my unit tests and demo verification.
