### ISSUE TITLE
Discrepancy of data

### ISSUE THREAD

**Issue by ea3hmj** [cosinekitty/astronomy#246]
Hi,

I am testing your library in c# and I find a small difference in the data obtained from the position around 0.5° elevation.

It happens with any selected body.

I attach a screenshot with 3 programs:

The first one ( the one above) is calculated with SPICE toolkit , the second one is provided by Horizonts System and the third one is using your library.

The first one is calculated, the second one is from Horizons and the third one is the one you use.

![image](https://user-images.githubusercontent.com/2368602/191909375-236dbec5-cc52-4af2-be60-79874dc3db71.png)

The code I use is:
`
time = new AstroTime(DateTime.UtcNow);
            Equatorial equ_2000 = Astronomy.Equator(body, time, observer, EquatorEpoch.J2000, Aberration.Corrected);
            Ecuatorial equ_ofdate = Astronomy.Equator(body, time, observer, EquatorEpoch.OfDate, Aberration.Corrected);
            Topocéntrico hor = Astronomy.Horizon(time, observer, equ_ofdate.ra, equ_ofdate.dec, Refraction.Normal);`

What am I doing wrong?

**Comment by cosinekitty** [comment]
I suspect this issue has to do with calculating the atmospheric refraction correction for an object below the horizon. Because such objects are not visible, there is no "right" or "wrong" way to do it. With that in mind, to make sure, I have a couple of questions.

Does this discrepancy also happen when the object's altitude angles are positive (above the horizon), or only when they are negative (below the horizon)?

Also, can you provide the latitude and longitude you are using for the observer's location? This will help me diagnose the issue.

**Comment by ea3hmj** [comment]
![image](https://user-images.githubusercontent.com/2368602/192013404-e12d775c-a2f9-4e5e-8537-7e4e5b8e1e1b.png)

Error remains.

I pass the height in metres to your engine

**Comment by ea3hmj** [comment]
In SPICE I use spkezr_c with "LT+S" in aberration correction.

https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/spkezr_c.html

**Comment by cosinekitty** [comment]
OK, I can see now that the difference is because of atmospheric refraction. I wrote the following test program to use your numbers and turn off atmospheric refraction:

```C#
using CosineKitty;

namespace MoonPos
{
    static class Program
    {
        static int Main(string[] args)
        {
            var observer = new Observer(41.5695334, 2.013942, 320.0);
            var time = new AstroTime(2022, 9, 23, 16, 58, 26);
            Equatorial equ_ofdate = Astronomy.Equator(Body.Moon, time, observer, EquatorEpoch.OfDate, Aberration.Corrected);
            Topocentric hor = Astronomy.Horizon(time, observer, equ_ofdate.ra, equ_ofdate.dec, Refraction.None);
            Console.WriteLine($"Az={hor.azimuth:F4}, Alt={hor.altitude:F4}, RA={hor.ra:F5}, DEC={hor.dec:F5}");
            return 0;
        }
    }
}
```

Then I get the following output:

```text
Az=287.7357, Alt=0.6774, RA=10.51145, DEC=13.63492
```

The important change is using `Refraction.None` instead of `Refraction.Normal` in the call to `Astronomy.Horizon`. This matches the SPICE option "LT+S", which corrects for light travel time and stellar aberration. Because SPICE "LT+S" does not correct for atmospheric refraction, to compare with Astronomy Engine we need to turn off refraction correction in Astronomy Engine also.

The function `Astronomy.Equator` always corrects for light travel time, and because we pass the option `Aberration.Corrected`, it corrects stellar aberration also. (Incidentally, neither of these options cause a significant change for the Moon because it is so close to the Earth, and its transverse speed is very slow. But they both matter more for other solar system bodies.)

As you can see, refraction makes a significant difference in the altitude angle for any object near the horizon, and consequently makes a big change in rise/set times.

I hope this helps!

**Comment by ea3hmj** [comment]
Indeed, now the data are the same, but I have a doubt, are they correct?

Thank you very much for your help

**Comment by cosinekitty** [comment]
I believe the calculations are reliable and accurate within arcminute error tolerances, because of automated tests that run every time I make a change. Every function in Astronomy Engine has a test that verifies against authoritative data. (In fact, I have a strict rule that I never add anything to Astronomy Engine without first creating a test based on reliable data.) Calculations are verified using data generated by JPL Horizons, the US Naval Observatory, NOVAS C 3.1, Stellarium, online tables from Fred Espenak, and other sources. Many of the calculations are verified through multiple independent methods from different sources. I have also compared with online calculators like Heavens Above. It is always possible that some bug exists, but at the moment, there are none that I know of. I'm always open to bug reports and I will do my best to fix anything as soon as discovered.

**Comment by ea3hmj** [comment]
I don't mean your engine, I mean using the way of applying the aberration to the calculations.

**Comment by cosinekitty** [comment]
Aberration correction is sometimes useful, other times it is counterproductive. The correction is small: between 0 and 22 arcseconds, depending on the direction of the object relative to the Earth's velocity vector. If you want to know an object's apparent position in the sky using actual measured angles, then you should use aberration correction. If you want to know the object's position relative to fixed background stars, it's better to omit aberration correction.

For example, if you are trying to use the known pattern of stars in a constellation to locate a dim planet like Uranus, and you know the uncorrected RA/DEC of nearby stars, it's a little better to leave Uranus's position uncorrected also. This is because the stars and the planet will both have about the same amount of aberration, so you don't want to correct one but not the other.

I hope I'm explaining this understandably.

**Comment by ea3hmj** [comment]
Understood.

Thank you very much again.
