### ISSUE TITLE
Discrepancy in Altitudes for Different Functions

### ISSUE THREAD

**Issue by JArjoon** [cosinekitty/astronomy#271]
Using the exact same Observer class, when calculating the altitude for solar noon, the altitude given by SearchHourAngle seems too high according to SearchAltitude, as when one uses SearchAltitude to look up altitudes _below_ solar noon the function returns null for values up to 0.05 degrees below the altitude given by SearchHourAngle. The issue is different for solar midnight however, as SearchAltitude returns a time, but it's the same time for every value less than 0.01 degrees above solar midnight.

Further, when one plugs the altitude given by SearchHourAngle into SearchAltitude, one gets a different time than the one given by SearchHourAngle.

Note; Both solar noon and solar midnight are more than 15 minutes apart from the date of the nearest valid altitude above or below.

**Comment by cosinekitty** [comment]
I can see how this would be a problem. SearchAltitude didn't exist in earlier versions of Astronomy Engine; there was only SearchRiseSet. I added SearchAltitude as a more general function to support calculation of civil twilight, nautical twilight, and astronomical twilight times. These are all searches for the small negative altitudes -6&deg; -12&deg;, and -18&deg; respectively.

Given a body and a fixed altitude, SearchAltitude searches for when the body goes from below the fixed altitude to above the fixed altitude.

More formally, it defines a function $f(t)=\left(a(t)-a_0\right)K$, where $a(t)$ is the altitude of the body at time $t$, $a_0$ is the fixed altitude, and $K$ is a direction constant, either +1 or -1 to indicate whether you want to find a rising event or a sinking event.

Then SearchAltitude searches for the next time when $f(t)$ ascends from a negative value through zero. And of course, this doesn't work when $a_0$ is a local maximum, because then $f(t)$ never becomes positive.

I think the main problem is that SearchAltitude isn't as general as it sounds, and I need to add better documentation to explain its limitations.

**Comment by JArjoon** [comment]
It would be a good idea to also specify the atmospheric refraction indices you're using as well as whether you're calculating from the edge of a body or its centre, as the problem also crops up if one cross references the times between SearchHourAngle, SearchAltitude, and SearchRiseSet.

**Comment by cosinekitty** [comment]
Resolved in e12d2e88c628b37605e0ca793217f7fbde73d663 and 5087e4df281f3a31a4b156594bd90ece53bc2542.
