### ISSUE TITLE
need this library in dart language

### ISSUE THREAD

**Issue by ikuruzum** [cosinekitty/astronomy#281]
i want to make an application calculating planets positions and 
this is the only library i found suitable for this

**Comment by cosinekitty** [comment]
Hi @ikuruzum and welcome to the project. We have a discussion page about the topic of adding support for other programming languages. In particular, I wrote [this post](https://github.com/cosinekitty/astronomy/discussions/109#discussioncomment-4303671) there about what it takes to add support for a new language. The summary is, because I do not know Dart, and because it would require daily work over a span of about two months to complete, I would need a volunteer who is an expert in Dart (and its related toolset) and has time to commit to help me. If you or someone you know is willing to take on this role, please let me know.

**Comment by ikuruzum** [comment]
I can't help because I don't have a lot of time. I found a workaround, I'm writing it here in case someone else might need it: use flutter_js in pub dev. its fast enough to eval a library. imo you already know dart. thank you for the effort you put into this library
you're a legend

**Comment by cosinekitty** [comment]
Hi @ikuruzum, I'm glad you found a way to make something work. Would you consider adding a few notes (with links if you have some handy) about your workaround in the [programming language discussion page](https://github.com/cosinekitty/astronomy/discussions/109)? I'm sure this would be very helpful for other Dart developers, and would be much more visible there than in this now-closed issue.
