### ISSUE TITLE
Is it possible to calculate the positions of Lilith, south node, north node, AC and MC? 

### ISSUE THREAD

**Issue by zenchanhk** [cosinekitty/astronomy#282]
As titled. Many thanks for helps.

**Comment by cosinekitty** [comment]
I had to look up "Lilith" because I had never heard of it. It sounds like there are various definitions. Astronomy Engine currently supports finding apogee, the time when the Moon is farthest from the Earth in a given orbit. See the [SearchLunarApsis](https://github.com/cosinekitty/astronomy/tree/master/source/js#SearchLunarApsis) function.

I'm guessing by south node and north node you mean the times when the Moon reaches its southernmost or northernmost positions, but I'm not sure whether you are interested in ecliptic or equatorial systems of measurement. 

Or possibly you mean something else. Usually when I hear "nodes" I think of ascending or descending nodes, meaning when the center of the Moon crosses the ecliptic plane. If that's what you mean, you can take a look at the [SearchMoonNode](https://github.com/cosinekitty/astronomy/tree/master/source/js#SearchMoonNode) function.

Also, I don't know what AC and MC are supposed to mean.

**Comment by zenchanhk** [comment]
Yes, it's the apogee of lunar orbit.
> I had to look up "Lilith" because I had never heard of it. It sounds like there are various definitions. Astronomy Engine currently supports finding apogee, the time when the Moon is farthest from the Earth in a given orbit. See the [SearchLunarApsis](https://github.com/cosinekitty/astronomy/tree/master/source/js#SearchLunarApsis) function.

Yes, the nodes are points in space where two different orbits intersect: the orbit of the Moon around the Earth and the Sun’s orbit as it appears to move around the Earth. I guess it's equatorial system of measurement. It takes 18.5 years to circle the entire zodiac. Is it posssible to find these nodes?
> I'm guessing by south node and north node you mean the times when the Moon reaches its southernmost or northernmost positions, but I'm not sure whether you are interested in ecliptic or equatorial systems of measurement.

![Image](https://kathrynhocking.com/wp-content/uploads/2019/07/Main-Social-Media-Quotes-blog-size-1.png)

**Comment by cosinekitty** [comment]
> Yes, the nodes are points in space where two different orbits intersect: the orbit of the Moon around the Earth and the Sun’s orbit as it appears to move around the Earth. I guess it's equatorial system of measurement. It takes 18.5 years to circle the entire zodiac. Is it posssible to find these nodes?

These nodes can be calculated by calling SearchMoonNode as mentioned above. The plane of the Earth's orbit around the Sun is called the ecliptic plane, which is different from the equatorial plane (the plane passing through the Earth's equator). The ascending node is when the center of the Moon passes through the ecliptic plane from south to north, and the descending node is when it passes from north to south.

**Comment by zenchanhk** [comment]
Thanks so much for your kind help. By the way, which function should I used to determine if a planet is in retrograde?

**Comment by cosinekitty** [comment]
I would recommend writing a helper function to calculate the ecliptic longitude of a body as seen from the Earth. It can call [GeoVector](https://github.com/cosinekitty/astronomy/tree/master/source/js#GeoVector) to obtain a geocentric vector in equatorial coordinates. Then pass that vector to the [Ecliptic](https://github.com/cosinekitty/astronomy/tree/master/source/js#eclipticeqj--eclipticcoordinates) function to convert it to ecliptic angles. The helper function would then return the ecliptic longitude from the resulting `elon` value returned by Ecliptic.

Once you get the helper function working, call it twice. The first time pass in the desired body and a time slightly before (perhaps 1 minute) the time you are interested in. The second time, pass in a time slightly after the time you are interested in.

Subtract the two resulting ecliptic longitudes. If the difference is positive, the body is moving prograde; if negative, it is moving retrograde.

**Comment by zenchanhk** [comment]
Awsome，highly appreciated for your so kind help.
