### ISSUE TITLE
newbie : Where to find Information

### ISSUE THREAD

**Issue by cullsin** [cosinekitty/astronomy#286]
Hi, 

I am a newbie into this group. The one side of the coin is pure astro math's. The other side of the coin is that 
interpret towards human's life. Please suggest where I can find information about that connection's and 
tutorial?

Thanks,
Raja K

**Comment by cosinekitty** [comment]
Astronomy Engine is designed purely for calculation of physical behavior of solar system objects, coordinate conversions, etc. Everything in it is verified in comparison with authoritative reference sources. I am not a believer in astrology, so I am probably the wrong person to ask about that second part!

**Comment by cullsin** [comment]
Thanks. Let me find that appropriate source.

**Comment by cullsin** [comment]
Hi,

According to astrology, there are 27 constellations. certain constellation belongs to certain planet. Is this real as of today?

I have a limited knowledge and I do not have any one to educate. So please don't mind about my questions 

Raja K

**Comment by cosinekitty** [comment]
The planets appear to be in a given constellation at a given time as seen from the Earth. Observers somewhere else in the solar system (another planet or a spacecraft far from Earth) will see the planets in different constellations because they are observing from a different angle. I can't think of what it would mean to say a planet belongs to a constellation in any permanent sense.

Constellations themselves are artificially constructed regions of the sky. In 1922, the International Astronomical Union (IAU) [agreed upon 88 constellations](https://www.iau.org/public/themes/constellations/) that astronomers use for conveniently mentioning various regions of the observable sky. Astronomers have continued to use these rectilinear borders to this day. The 88 IAU constellations are what Astronomy Engine uses in its [Constellation](https://github.com/cosinekitty/astronomy/tree/master/source/js#constellationra-dec--constellationinfo) function, which allows you to know what constellation any point in the sky belongs to, given its right ascension (RA) and declination (DEC).

I personally don't think constellations mean anything. They are random patterns of stars that happen to vaguely resemble different things to different cultures over time. We know that stars we see are all orbiting the galaxy at different speeds and moving in different directions. Over the span of hundreds of thousands of years, all of these patterns we see will change and become unrecognizable from their current arrangement. Ascribing human-oriented meanings to them would be like some tiny creature who lives for a few minutes seeing clouds in the sky, deciding to name them, and believing they mean something about itself and its fellow tiny creatures.

**Comment by cullsin** [comment]
Hi, 

I am looking into the planet's position for the given latitude and longitude of an earth.  
[http://cosinekitty.com/solar_system.html](url)

I need coordinates for the Sun as well. Your solar system web page needs to show that information. Please suggest. Also, Please advise which method from the astronomy engine gives this information. I did not find any samples.   

Please suggest.

Raja K

**Comment by cullsin** [comment]
Thanks. Can you please suggest a method in the astro engine module that
returns the plant positions?

Raja K

**Comment by cosinekitty** [comment]
That same positions.js demo shows the Sun, Moon, and planets:

```txt
$ node positions 30.5 -90.7 
UTC date = 2023-02-28T13:31:55.643Z

BODY           RA      DEC       AZ      ALT
Sun         22.73    -8.06   106.88    12.19
Moon         5.49    26.26     8.16   -32.33
Mercury     21.91   -14.95   120.01    17.76
Venus        0.62     3.24    82.41    -5.55
Mars         5.16    25.35    13.61   -32.41
Jupiter      0.73     3.51    81.30    -6.87
Saturn      22.10   -13.07   116.71    16.83
Uranus       2.86    16.07    51.01   -24.39
Neptune     23.68    -3.37    95.30     2.85
Pluto       20.12   -22.62   146.29    28.83
```

**Comment by cullsin** [comment]
Hi, 

I run the script for the given input. It is not matching with my planet positions mentioned in one of the astrology platform ( astrosAge app) . I have attached the screen shot for your refence. 

When I run the command, I got the below result. `node positions.js 10.786 79.137 1981-08-07T23:10:00.000Z`

Note : * When you debug or try to match my result, please do the `%` operation of `30 degree`. For example if ` sun is in 70 degree` then in my chart it shows as `70 % 30 = 10 degree` as per my calculation 

`BODY           RA      DEC       AZ      ALT`
`Sun          9.20    16.16    68.12   -19.55`
`Moon        15.06   -12.11   264.55   -67.59`
`Mercury      9.07    18.49    66.43   -16.97`
`Venus       11.27     6.02    65.18   -51.70`
`Mars         7.02    23.40    68.03    11.62`
`Jupiter     12.49    -1.90    61.42   -71.71`
`Saturn      12.45    -0.46    58.51   -70.47`
`Uranus      15.60   -19.13   250.73   -58.97`
`Neptune     17.46   -21.89   250.82   -32.54`
`Pluto       13.78     7.05   348.79   -71.59`

![info](https://user-images.githubusercontent.com/5137598/222782500-4d438e24-49a7-4df5-ac22-32317f630a0c.jpeg)

**Comment by cosinekitty** [comment]
I think two things are happening:

* Your screenshot does not show the same time as you gave to `positions.js`. Or at least I can't tell what time and date you gave it. Can you double check this?
* More importantly, I suspect the "Degree" number is an ecliptic longitude, not an equatorial right ascension (RA) or declination (DEC).

Assuming you want geocentric ecliptic longitudes, not heliocentric longitudes, here is an example of how to calculate that:

```javascript
const Astronomy = require('./astronomy.js');

const observer = new Astronomy.Observer(10.786, 79.137, 0.0);
const time = Astronomy.MakeTime(new Date('1981-08-07T23:10:00.000Z'));
const bodyList = [
    Astronomy.Body.Sun,
    Astronomy.Body.Moon,
    Astronomy.Body.Mercury,
    Astronomy.Body.Venus,
    Astronomy.Body.Mars,
    Astronomy.Body.Jupiter,
    Astronomy.Body.Saturn,
    Astronomy.Body.Uranus,
    Astronomy.Body.Neptune,
    Astronomy.Body.Pluto
];


console.log(`Body      Longitude    Latitude`);

for (let body of bodyList) {
    // Calculate J2000 equatorial coordinates of the body as seen from the Earth.
    const equator = Astronomy.Equator(body, time, observer, false, true);

    // Convert equatorial coordinates to ecliptic coordinates.
    const ect = Astronomy.Ecliptic(equator.vec);

    console.log(`${body.padEnd(8)} ${ect.elon.toFixed(3).padStart(10)} ${ect.elat.toFixed(3).padStart(11)}`);
}
```

The output looks like this:

```text
Body      Longitude    Latitude
Sun         135.330      -0.000
Moon        226.697       4.992
Mercury     132.814       1.662
Venus       167.313       1.203
Mars        103.744       0.698
Jupiter     187.252       1.178
Saturn      186.174       2.284
Uranus      236.056       0.203
Neptune     262.266       1.339
Pluto       201.921      16.889
```

**Comment by cullsin** [comment]
Hi, 

I am so sorry for the confusion. I gave you the wrong time & date. I did not notice UTC. 

I need a degree calculation from the given latitude and longitude from the earth. Below is the data for my planet's position
` Place: Thanjavur, Tamilnadu, India ( latitude - 10.786, longitude - 79.137, 0.0 )`
` Time : July 8th 1981, 11:10 PM IST Timezone`  

Please suggest the planet's position with the attached image above.

**Comment by cosinekitty** [comment]
I'm confused because the code sample I showed does calculate the position for a given observer on the Earth. You now have examples for planet positions expressed three different coordinate systems: horizontal, equatorial, and ecliptic. Is there some other orientation system you need? I think you need to get clarity on exactly what you are doing; otherwise, it is hard to help you.

**Comment by cullsin** [comment]
I am sorry for the confusion; I did not do anything. I just ran the Date of birth, latitude, and longitude in the astrology app `astrosage` and attached the image above. These calculations are similar across most of the platforms in astrology. Your recent output has only latitude, longitude and no planetary positions. 

I got the online website below 
`https://instaastro.com/vedic-astrology/planetary-positions/` 

Can you please replicate the same results through our script or code?

**Comment by cosinekitty** [comment]
> Your recent output has only latitude, longitude and no planetary positions.

Those numbers are ecliptic latitudes and longitudes, and they *are* planetary positions, expressed ecliptic coordinates. I was trying to help by providing a third coordinate system to use. In total I have shown you how to calculate planet positions in three different systems:

* Horizontal (altitude, azimuth based on given observer's horizon)
* Equatorial (right ascension, declination based on the plane of the Earth's equator)
* Ecliptic (latitude and longitude referenced to the Earth's orbital plane)

Yet you keep saying I am not showing you how to calculate planet positions, which is frustrating.

Astronomy Engine is available for anyone to use, and I'm willing to help explain how it works and to solve problems with it. I'm also happy to help explain astronomy concepts. This is my act of public service in the spirit of fostering scientific education.

However, I have a policy of not doing people's work for them. I feel like you are not really clear on what you are trying to calculate, but you just want answers that match what some other program calculates, and you want me to figure it out for you without you understanding it. This is outside my mission statement.

I think if you spent some time learning more about astronomy coordinate systems and work through some calculations, and by trial and error compared your results to the other programs, you could figure this out.

**Comment by cullsin** [comment]
> Yet you keep saying I am not showing you how to calculate planet positions, which is frustrating.

I'm sorry, but you have mistaken me. You're showing a result. But I need to match the result from the Actual Results shown on this website so that I understand the direction to proceed. 

`https://instaastro.com/vedic-astrology/planetary-positions/`

> However, I do not do people's work for them. I feel like you are not really clear on what you are trying to calculate, but you just want answers that match what some other program calculates, and you want me to figure it out for you without you understanding it. This is outside my mission statement.

Again. I do not want to confuse you with an example or wrong information. So I shared the website to ease your finding. I did compare the results. Since it is not showing the correct number, I reach out to you.

**Comment by cullsin** [comment]
Can you please direct me? I am waiting for your response.

**Comment by cosinekitty** [comment]
I don't know what coordinate system these other programs are using. When I see something like "FullDegree", it doesn't tell me anything. There are an unlimited number of different orientations that someone could use to describe a point in the sky. That is the most important thing you need to figure out.

It is most likely a form of ecliptic longitude. I suggest trying a few calculations for a given planet at times a few weeks apart. Something distant like Jupiter or Saturn will eliminate sensitivity to time zones or location on the Earth. Record the results, perhaps in a spreadsheet. Then calculate ecliptic longitudes for the same planet at the same times using Astronomy Engine as I showed above. The numbers may be very different, but perhaps there is an offset of some kind between them. Try subtracting the respective numbers and see if there is a pattern. You would be looking for a difference between the two that is consistent over time.

If that doesn't work, I would then try equatorial longitude, which is called right ascension (RA). Keep in mind that Astronomy Engine calculates RA in sidereal hours. You need to multiply by 15 to convert to degrees.

If all else fails, try getting some graph paper and a protractor and start plotting things on it, using numbers from both Astronomy Engine and the other programs. It could be that seeing the angles physically represented rather than looking at numbers will reveal some insight.

Also, you could try looking to see if there is some reference source that explains what these numbers mean. If you don't know what they mean (and I certainly don't), there is little chance of calculating them.
