### ISSUE TITLE
Current moon phase?

### ISSUE THREAD

**Issue by stefxx** [cosinekitty/astronomy#302]
Hi! Great library, thanks for creating it!

There is just one thing I can't figure out: how do I get the current moon phase (from the 8 phases, New moon, Waxing Crescent, First quarter, Waxing Gibbous, Full moon, Waning Gibbous, Last quarter, Waning Crescent)? 

I use this to get the degrees
`Astronomy.MoonPhase(New AstroTime(Now())`

but how do I properly translate that to a phase?

Thanks!

**Comment by stefxx** [comment]
I did find this table:

![image](https://user-images.githubusercontent.com/20107364/232336303-3dbe8296-25d6-4597-900f-48f604c971e7.png)

What is the best way to get the moon age?

**Comment by cosinekitty** [comment]
Hi @stefxx and welcome to the project!

About phases: You are on the right track. The `MoonPhase` function returns the Moon's ecliptic longitude relative to the Sun's ecliptic longitude. When this value changes from 359.9999... degrees to 0.0 degrees, we call that instant in time the new moon. It is the moment in time that the center of the Moon and the center of the Sun have the same ecliptic longitude, as viewed from the center of the Earth.

When `MoonPhase` returns 90.0 degrees, that is first quarter. Technically, any angle between 0 and 90 is a waxing crescent, although as you get between 80 and 90 degrees, people are going to have a hard time discerning a crescent shape from a "half full" shape characteristic of first quarter phase.

So in part, your question depends on subjective value judgments. It depends on what you are trying to do. If you want to find the exact moment when the Moon reaches a given phase angle, you would be better off using `SearchMoonPhase` instead. If you want to pick one of the eight shapes that the Moon most closely resembles, you could divide the phase angle by (360/8) = 45 degrees and round to the nearest integer.  This will give you a number 0..8. If the number is 0 or 8, you could say it is closest to being a new moon. If it is 1, waxing crescent, if 2, first quarter, etc.

However, you may implement this rounding idea and end up feeling it is not right. It can say the moon is "new" when you can clearly see it is a very thin waxing crescent. So this gets into the question of when the Moon is first visible after being new, which is a very complicated question, beyond the scope of Astronomy Engine.

About lunar days, I do have an example of calculating them in a Python demo program [lunarday.py](https://github.com/cosinekitty/astronomy/blob/master/demo/python/lunarday.py). It basically comes down to breaking the longitude circle into 30 equal parts (dividing by 12 degrees) instead of 8 equal parts (dividing by 45 degrees).

I hope this helps!
