### ISSUE TITLE
Please for imformation about time limits

### ISSUE THREAD

**Issue by milen-prg** [cosinekitty/astronomy#311]
Please to give some information about the time limits of calculations accuracy.
For example, about the equatorial position of the Sun for 202023 year the libnova, pyephem and this astronomy library returns absolutely different results. (unfortunately, the swissephem is not free for such long times).

**Comment by cosinekitty** [comment]
These 3 libraries should give consistent results. If they are different, there is something else happening. Can you give specific details about how you are testing them and what the numbers are?

**Comment by milen-prg** [comment]
I try really big date: 20 2023 / 6 / 21 and the results (equatorial coords in degrees) for the SUN are:

PyEphem:
RA = 114:10:32.1; DEC = 65:07:40.3

Libnova:
RA = 275.47; DEC = -3.98704

Astronomy (this):
RA = 98.238405; DEC = 4.078962

The 3 libraries returns some results, without any error message.
It is true, that I can't check this. The free astronomical software, which I tried ("Cartes du ciel", etc.), returns message about time limit up to 2500-3000 year. I'm not astronomer and may be it is absolutely impossible to make calculations for such  enormous time periods (even, I'm wonder how in the encyclopedias are given some constellations forms changes in millions years...).

Only the library swissephem (https://www.astro.com/horoscope) - C and PySwisseph, the free part, uses external files for more precisely calculations, but it gives message that are necessary other files out of the range -3001:3002 years. On their site are additional catalogues, but with special access, so I can't try their library for such long periods of time.
Because of that, I thought that your Astronomy library can use some files from your Ephemeris project to achieve more high accuracy in such a manner.

**Comment by cosinekitty** [comment]
Yes, that is correct. As you go farther in the future or past, chaotic behavior of an N-body gravitational system makes predictions more and more difficult.

Astronomy Engine calculates the Earth's position around the Sun (and therefore, the Sun's position as seen from the Earth) using the VSOP87 model. This model is a semi-analytic best-fit for the DE405 ephemeris. They claim to have high accuracy for &plusmn;4000 years from the present, but they are not supported or reliable outside that range.

Also, because you are calculating equatorial coordinates, you also introduce long-term unpredictability of the Earth's axis tilt. Astronomy Engine uses a truncated IAU2000b model for precession and nutation. This is highly accurate over several centuries, but I doubt it can be extrapolated reliably that far into the future.
