### ISSUE TITLE
Beginning of an ascending period of the Moon

### ISSUE THREAD

**Issue by serotonyn** [cosinekitty/astronomy#315]
Hi there,

I hope this message finds you well. I've been using the Astronomy library and I'm interested in calculating the "Beginning of an ascending period of the Moon" and the "Beginning of a descending period of the Moon." However, I'm not sure about the appropriate functions or methods to use for these calculations.

I've gone through the documentation and source code, but I couldn't find specific details on how to achieve this. I'd greatly appreciate it if you could provide guidance on how to calculate these points in time using the library.

Could you kindly direct me to the relevant functions or methods and provide some example usage or guidance on how to achieve these calculations? Any additional insights or explanations would be highly valuable.

The picture includes blue lines on 30, 1, 13 and 28 august. I'm aiming to understand how to achieve this using the library.
![image](https://github.com/cosinekitty/astronomy/assets/22910212/e3b2acef-f6da-4cb4-8a7b-c21aae7472a5)

Thank you very much for your time and assistance.

Environment:

Astronomy Library Version: (lastest)
Programming Language: (e.g., JavaScript)

If there's any specific information or documentation that I might have missed, please let me know. I'm eager to learn and improve my understanding of these calculations.

Thank you for your help!

**Comment by cosinekitty** [comment]
If I understand you, I think you are asking for when the Moon reaches its most northern or most southern position in each orbit. In other words, when the Moon is farthest north, it then begins to move south again, and when it is farthest south, it begins to move north again.

Is this what you mean?

If so, there is a second question: are you interested in ecliptic latitudes (based on the ecliptic plane) or in declinations (based on the Earth's equatorial plane)? Depending on your answer, the calculations will give different times, because the two orientation frames are tilted with respect to each other.

**Comment by serotonyn** [comment]
Thank you for your prompt response and for seeking clarification. Yes, you've understood my question correctly. I'm indeed looking to calculate the points when the Moon reaches its most northern or southern position during its orbit, and the transitions from those points as it starts moving in the opposite direction.

Regarding the orientation frame, I'm interested in both ecliptic latitudes and declinations. It would be valuable to have **calculations for both** frames so that I can compare and analyze the results based on the specific context of my project.

My goal is to create a calendar that looks like the one in the picture above. So ultimately what I want is to be able to calculate both.

Thank you once again for your expertise and support.

**Comment by cosinekitty** [comment]
Great, I'm glad it is making sense. I added a Node.js demo called [moon_north_south.js](https://github.com/cosinekitty/astronomy/blob/master/demo/nodejs/moon_north_south.js) that shows how to do this. There was no easy built-in function for calculating the latitude extremes in Astronomy Engine, but this shows how to approach it by defining a custom search function.

An example of running the program:

```
 node moon_north_south 2023-08-22
2023-09-10T07:47:00.420Z  Moon next reaches maximum ecliptic latitude = 5.1662436.
2023-08-28T08:26:14.233Z  Moon next reaches minimum ecliptic latitude = -5.1107593.
2023-09-08T13:13:01.641Z  Moon next reaches maximum declination = 28.1783302.
2023-08-26T20:18:11.883Z  Moon next reaches minimum declination = -28.1066748.
```

I verified the calculations are correct using JPL Horizons.

**Comment by serotonyn** [comment]
Thank you so much for the help and for providing the demo. I truly appreciate the effort you've put into creating this resource.

**Comment by cosinekitty** [comment]
You are most welcome! Also, I just pushed an update to the moon_north_south.js demo. There was a bug that caused the search to fail for certain starting dates. Trying to find the solution with a single 30-day window is too aggressive, because more than one min/max can occur within that window. So now it splits the search into 10-day intervals and keeps going until it finds the solution. This is a safe interval because it is less than half of the Moon's fastest possible orbital period.
