### ISSUE TITLE
Calculation in parallel?

### ISSUE THREAD

**Issue by jaredramirez** [cosinekitty/astronomy#343]
Hey there, thanks for the great library!

I'm using the C version of the Astronomy Engine in a multi-threaded application. When attempting to do many planetary calculations in parallel, I'm getting inconsistent/non deterministic results back from Astro Engine. Can this library be used in this way?

**Comment by cosinekitty** [comment]
Yes it can, with the possible exception of calculating Pluto's position. There could be some thread-safety issues there because it uses in-memory caching without any locks. If you can lock a mutex around calculating Pluto's position, everything else should be completely thread-safe.

However, perhaps I am wrong in my belief, because I have never tested multi-threaded operation. I would like to help you get to the bottom of this, and make any necessary fixes to Astronomy Engine.

Would you be willing to provide an example program that demonstrates the problem? I would like to try reproducing the problem myself to help diagnose it.

**Comment by jaredramirez** [comment]
Ahh this is consistent with the behavior I'm seeing, it's only Pluto that's causing inconsistencies. I'm not an expert C programmer, can you provide any more details on how I could lock a mutex around calculating Pluto's position?

As far as a reproducible example, I'm actually using this library in a Haskell application (via C FFI), so I don't have this at the moment.

**Comment by jaredramirez** [comment]
I was able to get this to work with the following:
```c

pthread_mutex_t pluto_mutex = PTHREAD_MUTEX_INITIALIZER;

void my_func() {
  if (*body == BODY_PLUTO) {
    pthread_mutex_lock(&pluto_mutex);
    vector_result = Astronomy_GeoVector(*body, cur_time, *abberation);
    pthread_mutex_unlock(&pluto_mutex);
  } else {
    vector_result = Astronomy_GeoVector(*body, cur_time, *abberation);
  }
}
```

The issue now is that it's quite slow to do any pluto calculations!

Is is possible to use per-thread in-memory caching inside astronomy engine? Again not a C expert, so no idea if that possible or very hard

**Comment by cosinekitty** [comment]
I probably should fix this someday, especially because I was already concerned about it. See [this comment in astronomy.c](https://github.com/cosinekitty/astronomy/blob/61dc07020aaa6885d2c7f688a4d82beaf6edb9ef/source/c/astronomy.c#L4556):

```c
/* FIXFIXFIX - Using a global is not thread-safe. Either add thread-locks or change API to accept a cache pointer. */
static body_segment_t *pluto_cache[PLUTO_NUM_STATES-1];
```

The main problem I run into is, I don't want to break the code for people on micro-controllers or other environments where there is no concept of multi-threading. So I would probably need to come up with some kind of opt-in `#define` symbol to upgrade to using thread-safety.
