### ISSUE TITLE
SearchRiseSet function that returns null for a defined star using DefineStar function

### ISSUE THREAD

**Issue by Zoliex** [cosinekitty/astronomy#370]
Hi, I've decided to create an issue for this module because i encountered an issue when using the module. As I was trying to calculate the rise and set of M31'coordinates (using the DefineStar function), the function SearchRiseSet, returned me null two times. I don't know if it's a normal and know issue and I need your help.

You will find my code and the result in the console.
I wish you will be able to help me.

Best regards,
Enzo C.

```
const Astronomy = require("astronomy-engine")

//Define for m31
Astronomy.DefineStar(Astronomy.Body.Star1, 0.712775, 41.0445648148, 1000)

//Defining an Observer at Paris
const observer = new Astronomy.Observer(48.8534951, 2.3483915, 1.5)

const rise = Astronomy.SearchRiseSet(Astronomy.Body.Star1, observer, +1, new Date(), 1)
const set = Astronomy.SearchRiseSet(Astronomy.Body.Star1, observer, -1, new Date(), 1)

console.log("rise: ", rise)
console.log("set: ", set)
```

```
PS C:\Users\**\code\projects\tests> node riseset.js
rise:  null
set:  null
```

**Comment by cosinekitty** [comment]
Hi @Zoliex and welcome to the project! It does look like something is wrong here. I will take a look over the weekend to see if I can figure this out. Thanks for reporting it!

**Comment by cosinekitty** [comment]
OK, I see what is happening. Because M31 has a declination of about 41 degrees, but an observer in Paris is about 49 degrees north of the equator, it means that observer is too far north for M31 to ever go below the horizon. In fact, M31 will never appear below 8 degrees above the horizon in Paris. Therefore, you can never see it rise or set. SearchRiseSet correctly returns null in this case.

**Comment by Zoliex** [comment]
Ok thanks, you're on fire !

**Comment by Zoliex** [comment]
But if you look on telescopius, the object has rise and set properties (set the location to paris and reload the page to see rise and set of m31 for paris) :
https://telescopius.com/deep-sky-objects/m-31/andromeda-galaxy/spiral-galaxy/galaxy/quasar

**Comment by cosinekitty** [comment]
I have to make a correction in what I wrote above: because Paris is about 49 degrees north of the equator, it is 41 degrees away from the north pole. This means anything in the sky more north than 41 degrees declination will never cross the horizon. This means M31 is right on the boundary. Adding a small lift due to atmospheric refraction causes it to never rise or set.

Also, when I use that page, I see that the minimum altitude angle is 0 degrees, which is consistent with my corrected understanding:

![image](https://github.com/user-attachments/assets/2fcfe9bc-1c28-4a8c-8eea-8f62c568350d)

**Comment by Zoliex** [comment]
Ok, thanks, but why can i get rise and set values for M31 ? (values below the graph on your screenshot)
