### ISSUE TITLE
Ecliptic and horizon intersection

### ISSUE THREAD

**Issue by cronvel** [cosinekitty/astronomy#53]
First, thanks for this great lib.

Is there a simple way to intersect the ecliptic with the horizon? I have explored the source code, and I can't find a way to do it. Since the horizon is not trivial due to atmospheric effect, it's too complicated for me.

Any idea?

**Comment by cosinekitty** [comment]
Hi @cronvel . That is an interesting one. Let me think about it. Which programming language are you using?

**Comment by cronvel** [comment]
Hi @cosinekitty , I'm using Node.js/Javascript!

**Comment by cosinekitty** [comment]
Hi again @cronvel . OK, great. So far it looks like I will need to add some new functionality. I just want to clarify. Are you trying to find the azimuths (compass directions) of the two places on the observer's horizon where the ecliptic intersects it?  Also, I'm curious what the use case is; in other words, why is that useful?  (It may affect how I implement it.)

**Comment by cronvel** [comment]
@cosinekitty Yes I could be interested in azimuth as well as other coordinates system for both points. In fact, it could be really nice if we could transpose easily from different coordinate systems. For my own use-case, my main interest (at the moment) is for **geocentric**, **spherical** and **apparent** coordinates in those systems:
* equatorial coordinate
* ecliptic coordinate
* horizon coordinate

I can manage equatorial/ecliptic transposition on my own (but it could be interesting anyway for the completeness of your nice lib), my math knowledge are enough for that, but when it comes to atmospheric refraction, *aberration*, and other non-trivial things (like dealing with non-UTC time), I'm helpless ^^ 

As for my use-case, I would like to build a sort of real-time astronomical clock, using web technologies (Node.js/Electron) and SVG, with a lot of stuff moving around a kind of 2D/3D compass, with some event tracking (conjunction/opposition, both in 3D and in 2D ecliptic projection). The **ecliptic/horizon intersection** is one of those moving things (along with various ecliptic/equatorial north/south pole, zenith/nadir, and so on -- that's why I need some way to transpose from/to those 3 coordinates system).
Also the clock would have the 3 modes mentioned above (equatorial/ecliptic/horizon), changing how things are projected.
For instance, all that would be geocentric, but maybe later I would add an heliocentric switch.

Also I'm currently just starting that hobby-project, benchmarked few libs, and selected yours, because it has almost all the features I need, small footprint, and the precision looks decent (checked against Stellarium). So for instance I just got a CLI program, until the core is ready for some fancy output ^^

**Comment by cosinekitty** [comment]
OK, thanks for all the details. I am going to create new issues for coordinate transformation. I agree it should be possible to convert from any coordinate system to any other, either directly or through a series of transformations.

I had some more thoughts about ecliptic/horizon intersection. There is a simple way to handle atmospheric refraction. At the horizon, you can assume refraction causes everything to appear 34 arcminutes higher than it really is. In other words, anything you see at the horizon is actually 34 arcminutes below the horizon. This is a typical value; exact values depend on temperature, pressure, and humidity, but most software doesn't bother because this fixed value is good enough.

So that means what you really want is the intersection of the ecliptic with a horizontal ring 34 arcminutes below the horizon, ignoring refraction. Once you find the azimuth there, it will be correct for the actual horizon with refraction.  Still, I would have to think about the best way to calculate that intersection.

**Comment by cosinekitty** [comment]
@cronvel See issue #54.

**Comment by cronvel** [comment]
@cosinekitty Ok, I will give it a try. If it's only 34 arcminutes, maybe I could ignore that for instance. Haha, I can see hours of web crawling for math formula!!! ^^

**Comment by cosinekitty** [comment]
Hi again, @cronvel .  I just merged support for coordinate transforms into the master branch as of commit 330b8447f3229aca8b98195ab0e217b778391e4c.  There is also a sample Node.js program `demo/nodejs/horizon.js` that shows how to find the intersection between the ecliptic and an observer's horizon. Equivalent support exists among JavaScript, C, and Python.

I will be interested to hear what you think.

**Comment by cronvel** [comment]
@cosinekitty Thanks a lot, I will give it a try this weekend! ;)

**Comment by cosinekitty** [comment]
The demo program for calculating intersection of the ecliptic and the horizon is finished for all supported languages: C, C#, Python, JavaScript. All are in the master branch.
