### ISSUE TITLE
Generator for Typescript

### ISSUE THREAD

**Issue by matheo** [cosinekitty/astronomy#79]
This is a feature request to add typings to the Javascript npm package.
That will be handly for the modern frontend frameworks out there :)

**Comment by cosinekitty** [comment]
Yes, that does make sense. I am familiar enough with TypeScript that I think I could convert the existing JavaScript code to TypeScript, then use the TypeScript compiler to build the JavaScript code from it. I could then make both available for people, depending on which is a better fit for their project. I will take a look at that over the next few days. It could take me a little while to finish because there are complications with how I generate documentation from source code, etc.

**Comment by matheo** [comment]
Awesome, I hope you get it running in a pretty smooth way without issues ;)

**Comment by cosinekitty** [comment]
I have started working on TypeScript support in a new experimental branch `typescript` (see commit c5738052b4f4d422c6cce0d29ee13899e68a99e5). I converted the JavaScript to TypeScript and got it to compile back to JavaScript. Both ts and js are available to developers who clone the repo. Where can I learn about providing the type signatures that help people who use npm packages? This is outside my expertise.

**Comment by matheo** [comment]
ok, I played with the branch and I found some issues:

1. For typescript to be useful we need some typings that are not generated because of the namespacing, so I removed it (I have nothing against it but doing some coding clean OOP let the compiler to generate it automatically, I got this one after solve some compilation issues: [astronomy.d.ts](https://gist.github.com/matheo/340a5b9413af2dd79d7e91fea0da0463)
2. I found some compilation issues due to this usage: `Astronomy.Search(fn, t1, t2, 1.0)`, where the fourth parameter is supposed to be an options object, what's that `1.0` supposed to be? `iter_limit`?
3. I found this usage too: `return Astronomy.Search(sun_offset, t1, t2)` so I made the complete options object optional.
4. As `Search*` methods returns `null | AstroTime` there are some methods that requires exception handling to compile, like `SearchSunLongitude`, `NextMoonQuarter`, `PeakEarthShadow`, `PeakMoonShadow`, `PeakPlanetShadow` (`PeakLocalMoonShadow` does validate correctly), `SearchLocalSolarEclipse`, `NextLocalSolarEclipse`. Those methods gave me typing errors when I cleaned the namespace.

I can fix these issues following your comments about them, and create a PR to the `typescript` branch for your evaluation.

**Comment by cosinekitty** [comment]
Hi Mateo,

That sounds great. I didn't think about the namespace very much when I
started the project. I am not an expert in JavaScript, but I had received
feedback from years ago that one should not "pollute" the caller's
namespace with too many exposed symbols.

And yes, because I use modern classes anyway, it makes a lot of sense to
use a class for the outermost Astronomy object, rather than a closure like
I did. I knew there would be a lot of internal details that I wanted to
hide from the outside world. Now that classes exist in JavaScript, and they
support private members, that is clearly the better choice.

I'm very happy that you are finding these issues, because I want this code
to be the highest possible quality for people. I will take a look at the
issues with Search in a few hours. Let me study them and I will reply again
then.

Don

**Comment by matheo** [comment]
All right,
I will commit my partial branch to let you run my refactored code.

I managed to bundle the code for browsers, so the `window.Astronomy` object will be kept as it is right now, but in the modern typescript frameworks we are encouraged to import only the required code from the libraries, so we could have `import { SearchSunLongitude } from 'astronomy-engine'` and the bundlers will not include all the other non-used functions in the final app :)

**Comment by cosinekitty** [comment]
@matheo Thanks for all your work on this. It has greatly improved the JavaScript code quality. I just did some follow-up work and miscellaneous cleanup in a series of commits to the `typescript` branch. Mostly I removed `export` from symbols that should remain private, and I reworked type declarations in JSDOC and TypeScript to be simpler and more consistent.

I would feel comfortable merging this into the master branch now. Is that a good idea from your point of view? I don't want to complicate the work you are doing on creating a new website.

**Comment by matheo** [comment]
Sure, I already saw the ticket and looks ok, you're the one knowing the API that you want to export publicly :)
Let's merge `typescript` to `master` and continue with the website PR.

**Comment by cosinekitty** [comment]
OK, it is done!

**Comment by matheo** [comment]
We forgot to close this via commit message, doing it manually.
