### ISSUE TITLE
Function to return physical data for each solar system body

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#94]
It would be nice to have a function that returns physical data for all supported bodies:

- Mass
- Equatorial, polar, and mean radii.

**Comment by cosinekitty** [comment]
I'm starting to think it makes more sense to provide constant declarations for invariant physical data, instead of a function. I have already started down this road, for example for the radii of Jupiter and its moons.

**Comment by cosinekitty** [comment]
I have added constants for polar and equatorial radii of the Sun, Moon, planets, and Jupiter's 4 largest moons. I needed these for the C raytrace demo. I will continue to add constants as needed. As it is, this issue is too open-ended to ever be considered "done", so I will close it now. More specific issues can be created later, as needed for a specific goal.

**Comment by meshula** [comment]
One piece of data I'm wondering if you've got, is the vector from the center of a planet to it's rotational pole, and also its magnetic pole? I'm imagining the vector might be in ecliptic plane and relative to the vernal equinox or something like that. Back when I was working on aligning Juno images, computing correspondences between the Juno position data and Jupiter was difficult due to a lack of commonly available data on Jupiter in a useful reference frame. That's why I ask.

**Comment by meshula** [comment]
(I ended up dead reckoning based on image recognizing features between frames)

**Comment by cosinekitty** [comment]
@meshula I would like to hear more about what you were doing with Juno images. That sounds very interesting!

About planet poles, there is a recently-added function `RotationAxis` for determining the rotation axis, and part of the returned data is exactly a unit vector that points in the direction of the planet's north pole from its center. See the [Python version of `RotationAxis`](https://github.com/cosinekitty/astronomy/tree/master/source/python#rotationaxisbody-time) for example.

I do not have any model of magnetic fields for planets. I doubt any scientist knows how to predict the future behavior of the Earth's magnetic field, nor that of any other planet. The physical processes are hidden deep inside these worlds and are somewhat mysterious.

**Comment by meshula** [comment]
Yeah, I think only Jupiter's magnetic field is well studied, beyond Earth, and probably out of scope for the library; 

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2018gl077312

It's been a few years since I wrestled with it.

I worked with Bill Dudney on the math a few years ago.

https://twitter.com/bdudney/status/1418206450506092560?s=20

Here's a picture of a full globe he created not too long ago.

https://twitter.com/bdudney/status/1448326812157632513?s=20

Here's a view of a projected strip 

https://twitter.com/bdudney/status/1458638536375033857?s=20

**Comment by cosinekitty** [comment]
That is a fascinating paper about Jupiter's magnetic field. It is even more complicated than I imagined. I am also impressed by your work on such a cool science mission as Juno!

**Comment by meshula** [comment]
Bill & I took part in the "citizen scientist" initiative part of the program, as citizen scientists :) It was continuously inspiring. I'm sure you've seen some of the incredible renderings people have made with the Juno data at this point, I'm just staggered by the whole thing, from Jupiter itself, to the openness of the science team at Juno, to the art people have created from all of that!
