### ISSUE TITLE
How to calculate the angle between Sun and Moon for a specific period of time?

### ISSUE THREAD

**Issue by zohozer** [cosinekitty/astronomy#98]
I do need to calculate the 12 degree (and multiply of) angle between Sun and Moon and I can't find a way to do this task using the python script. It is possible to modify the source-code to be able to achieve the desired result?

**Comment by cosinekitty** [comment]
If you want to find the traditional definition of moon phase (relative ecliptic longitude of the Moon with respect to the Sun), you can use the [MoonPhase](https://github.com/cosinekitty/astronomy/tree/master/source/python#moonphasetime) function:

```python
from astronomy import Time, MoonPhase
time = Time.Now()
phase = MoonPhase(time)
print(phase)   # 0 .. 360 degrees
```

If you want to find the actual angle between the Sun and Moon in 3D space, you can use the [AngleFromSun](https://github.com/cosinekitty/astronomy/tree/master/source/python#anglefromsunbody-time) function:

```python
from astronomy import Time, Body, AngleFromSun
time = Time.Now()
angle = AngleFromSun(Body.Moon, time)
print(angle)   # 0 .. 180 degrees
```

Does this help?

**Comment by zohozer** [comment]
Thank you for the reply. It is working but only for the current moment "Time.Now()"

I do need to generate a table for when the angle between Sun and Moon is exactly at multiples of twelve degrees as I need to determine the Lunar Day. So, for this case, the first example works better because it is returning something like "297.8186026067825" which I think is 297 degrees the angle between Sun and Moon?

I do need to generate a table with all the dates/times when the Sun-Moon angle is multiply of 12 which will help-me to determine the specific [Lunar Day](https://www.lunarium.co.uk/articles/about-lunar-days.jsp) for a period of time:

0-12 = First Lunar Day
12-24 = Second Lunar Day
24-36 = 3th
36-48 = 4th
48-60 = 5th
60-72 = 6th
72-84 = 7th
84-96 = 8th
96-108 = 9th
108-120 = 10th
120-132 = 11th
132-144 = 12th
144-156 = 13th
156-168 = 14th
168-180 = 15th
180-192 = 16th
192-204 = 17th
204-216 = 18th
216-228 = 19th
228-240 = 20th
240-252 = 21th
252-264 = 22th
264-276 = 23th
276-288 = 24th
288-300 = 25th
300-312 = 26th
312-324 = 27th
324-336 = 28th
336-348 = 29th
348-360 = 30th Lunar Day

More about the Lunar days here: https://www.lunarium.co.uk/articles/about-lunar-days.jsp

**Comment by cosinekitty** [comment]
OK, that is interesting! I did not know about lunar days. I created a demo for you to try:

https://github.com/cosinekitty/astronomy/blob/master/demo/python/lunarday.py

**Comment by zohozer** [comment]
Thank you. This solution it is working!

![LunarDays-calculator](https://user-images.githubusercontent.com/5983791/113752697-2b2e0900-9705-11eb-9ffa-108ef27b2bf8.png)

Do you have also a formula that can calculate the ["Void of course moon"](https://www.bustle.com/life/void-of-course-moon-astrology-meaning-explainer)? Very important to know when to NOT start new actions!

**Comment by cosinekitty** [comment]
The void course of the moon looks like a much more complicated and specialized concept. It also does not sound precisely defined (how large are the angles, which planets, etc.). My design goals for Astronomy Engine are to keep it as general as possible for a wide variety of uses, and limiting the size it grows to.

However, I will provide some ideas for how I would approach this:

Astronomy Engine can calculate which constellation a given point is within, using the [Constellation](https://github.com/cosinekitty/astronomy/tree/master/source/python#Constellation) function. You can calculate the required equatorial position coordinates (RA, DEC) of the Moon and planets using the [Equator](https://github.com/cosinekitty/astronomy/tree/master/source/python#constellationra-dec) function.

Currently there is no function to calculate the angle between arbitrary bodies (only the Sun and another body). For now, you could look inside astronomy.py at the internal function `_AngleBetween` to see how it calculates the angle between two arbitrary vectors. I will create another issue for exporting this function so outside callers can use it, because it is general purpose enough that many different applications could use it.

There is an exported generic [Search](https://github.com/cosinekitty/astronomy/tree/master/source/python#searchfunc-context-t1-t2-dt_tolerance_seconds) function that can be used to search for the times of just about any event you can imagine, so long as you can express the event in terms of a function that crosses from a negative value, through zero, to a positive value, at a given time of interest. This is the function that Astronomy Engine uses for searching for moon phases, sunrise/sunset times, maximum elongations, conjunctions, oppositions, etc. So `Search` could conceivably be used for finding when the Moon becomes less than a certain angle away from a given planet, etc.

I hope these ideas help!

**Comment by zohozer** [comment]
Yes, seems more complicated at first but if you understand how it is working, begins to be easy, like anything we already know.

The "Void of Course Moon" (VoC) it is always starts when the Moon don't have any more important aspects somewhere at the end of the current astrologic sign of the Moon and ends when the Moon enters the next zodiacal sign. For example if the Moon is in the sign of Aries, the VoC will be somewhere at the end of the Moon in Aries and ceases when the Moon enters the Taurus sign and so on.

A quite good explanation of VoC can be found here: https://www.moontracks.com/void_of_course_moon_dates.html

**Comment by cosinekitty** [comment]
I thought about this some more, and I think I have a fairly balanced idea. I have added issues #99, #100, #101 to the development plan, as things I will work on when I get the chance. I believe they are general enough to be included inside Astronomy Engine, and they will do most of what you will need. After they are done, you would then need to call the new functions for the Moon and whatever planets you are interested in, passing in relative longitude target angles like 0, 60, 120, 180.

It may be a few weeks before I get to this, because currently I'm in the middle of working on #67.

**Comment by zohozer** [comment]
Thank you for your hard work. I will keep an eye on this page!

**Comment by cosinekitty** [comment]
I'm closing this issue only because this work has been split into three new issues: #99, #100, #101. They will each remain open until completed and tested.

**Comment by cosinekitty** [comment]
@zohozer I created Python demos for both kinds of search: finding when the Moon makes interesting angles with the planets, and when the Moon crosses from one constellation to another. See [constellation.py](https://github.com/cosinekitty/astronomy/blob/master/demo/python/constellation.py) and [lunar_angles.py](https://github.com/cosinekitty/astronomy/blob/master/demo/python/lunar_angles.py). I think these should be enough to get you started. Please let me know how it goes.
